package com.amigoscode.springbootlearning.nextjsbasics.util;

import com.amigoscode.springbootlearning.nextjsbasics.entity.UserEntity;

import java.util.List;

public class UserData {

    public static List<UserEntity> getUsers() {

        return List.of(
                new UserEntity("Chethan", "Frontend Developer"),
                new UserEntity("Rahul", "Backend Developer"),
                new UserEntity("Ankit", "QA Engineer"),
                new UserEntity("Priya", "UI Designer"),
                new UserEntity("Amit", "DevOps Engineer"),
                new UserEntity("Sneha", "Business Analyst"),
                new UserEntity("Vikram", "Backend Developer"),
                new UserEntity("Neha", "Frontend Developer"),
                new UserEntity("Karan", "QA Engineer"),
                new UserEntity("Pooja", "Project Manager"),
                new UserEntity("Rohan", "Backend Developer"),
                new UserEntity("Aisha", "UI Designer"),
                new UserEntity("Arjun", "Frontend Developer"),
                new UserEntity("Meera", "Business Analyst"),
                new UserEntity("Nikhil", "DevOps Engineer"),
                new UserEntity("Kavya", "QA Engineer"),
                new UserEntity("Varun", "Backend Developer"),
                new UserEntity("Ananya", "Frontend Developer"),
                new UserEntity("Siddharth", "Project Manager"),
                new UserEntity("Ishita", "UI Designer"),
                new UserEntity("Harsha", "Backend Developer"),
                new UserEntity("Deepika", "QA Engineer"),
                new UserEntity("Manoj", "DevOps Engineer"),
                new UserEntity("Shreya", "Frontend Developer"),
                new UserEntity("Abhishek", "Business Analyst"),
                new UserEntity("Ritika", "UI Designer"),
                new UserEntity("Akash", "Backend Developer"),
                new UserEntity("Divya", "Project Manager"),
                new UserEntity("Suraj", "Frontend Developer"),
                new UserEntity("Nisha", "QA Engineer"),
                new UserEntity("Yash", "Backend Developer"),
                new UserEntity("Tanvi", "Business Analyst"),
                new UserEntity("Aditya", "DevOps Engineer"),
                new UserEntity("Preeti", "UI Designer"),
                new UserEntity("Rakesh", "Frontend Developer"),
                new UserEntity("Madhuri", "QA Engineer"),
                new UserEntity("Gaurav", "Backend Developer"),
                new UserEntity("Swathi", "Project Manager"),
                new UserEntity("Lokesh", "DevOps Engineer"),
                new UserEntity("Bhavana", "Business Analyst"),
                new UserEntity("Pradeep", "Frontend Developer"),
                new UserEntity("Aparna", "UI Designer"),
                new UserEntity("Chirag", "Backend Developer"),
                new UserEntity("Sonal", "QA Engineer"),
                new UserEntity("Naveen", "Project Manager"),
                new UserEntity("Keerthi", "Business Analyst"),
                new UserEntity("Tarun", "DevOps Engineer"),
                new UserEntity("Lavanya", "Frontend Developer"),
                new UserEntity("Vivek", "Backend Developer"),
                new UserEntity("Monika", "UI Designer"),
                new UserEntity("Aarav", "Frontend Developer"),
                new UserEntity("Vivaan", "Backend Developer"),
                new UserEntity("Aditya", "QA Engineer"),
                new UserEntity("Arjun", "DevOps Engineer"),
                new UserEntity("Sai", "UI Designer"),
                new UserEntity("Krishna", "Full Stack Developer"),
                new UserEntity("Rohan", "Backend Developer"),
                new UserEntity("Karthik", "Frontend Developer"),
                new UserEntity("Nikhil", "QA Engineer"),
                new UserEntity("Varun", "DevOps Engineer"),
                new UserEntity("Manoj", "Frontend Developer"),
                new UserEntity("Akash", "Backend Developer"),
                new UserEntity("Deepak", "QA Engineer"),
                new UserEntity("Harsha", "Frontend Developer"),
                new UserEntity("Vikram", "Full Stack Developer"),
                new UserEntity("Pranav", "Backend Developer"),
                new UserEntity("Abhishek", "DevOps Engineer"),
                new UserEntity("Siddharth", "Frontend Developer"),
                new UserEntity("Yash", "QA Engineer"),
                new UserEntity("Raj", "Backend Developer"),
                new UserEntity("Kiran", "Frontend Developer"),
                new UserEntity("Naveen", "Full Stack Developer"),
                new UserEntity("Suraj", "DevOps Engineer"),
                new UserEntity("Pavan", "Backend Developer"),
                new UserEntity("Ajay", "QA Engineer"),
                new UserEntity("Tarun", "Frontend Developer"),
                new UserEntity("Rakesh", "Backend Developer"),
                new UserEntity("Ashwin", "DevOps Engineer"),
                new UserEntity("Dinesh", "Full Stack Developer"),
                new UserEntity("Shyam", "QA Engineer"),
                new UserEntity("Mohan", "Frontend Developer"),
                new UserEntity("Ganesh", "Backend Developer"),
                new UserEntity("Vinay", "QA Engineer"),
                new UserEntity("Lokesh", "DevOps Engineer"),
                new UserEntity("Tejas", "Frontend Developer"),
                new UserEntity("Sandeep", "Backend Developer"),
                new UserEntity("Bhavesh", "Full Stack Developer"),
                new UserEntity("Chirag", "QA Engineer"),
                new UserEntity("Nitin", "Frontend Developer"),
                new UserEntity("Uday", "Backend Developer"),
                new UserEntity("Kunal", "DevOps Engineer"),
                new UserEntity("Hemant", "QA Engineer"),
                new UserEntity("Parth", "Frontend Developer"),
                new UserEntity("Rituraj", "Backend Developer"),
                new UserEntity("Ansh", "Full Stack Developer"),
                new UserEntity("Dhruv", "QA Engineer"),
                new UserEntity("Aryan", "DevOps Engineer"),
                new UserEntity("Tushar", "Frontend Developer"),
                new UserEntity("Jatin", "Backend Developer"),
                new UserEntity("Mayank", "Full Stack Developer"),
                new UserEntity("Aditi", "Frontend Developer"),
                new UserEntity("Sanya", "Backend Developer"),
                new UserEntity("Isha", "QA Engineer"),
                new UserEntity("Riya", "DevOps Engineer"),
                new UserEntity("Pallavi", "UI Designer"),
                new UserEntity("Nandini", "Full Stack Developer"),
                new UserEntity("Anusha", "Backend Developer"),
                new UserEntity("Keerthana", "Frontend Developer"),
                new UserEntity("Bhavya", "QA Engineer"),
                new UserEntity("Shruti", "DevOps Engineer"),
                new UserEntity("Pooja", "Frontend Developer"),
                new UserEntity("Megha", "Backend Developer"),
                new UserEntity("Lavanya", "QA Engineer"),
                new UserEntity("Divya", "Frontend Developer"),
                new UserEntity("Swathi", "Full Stack Developer"),
                new UserEntity("Aparna", "Backend Developer"),
                new UserEntity("Sneha", "DevOps Engineer"),
                new UserEntity("Rashmi", "Frontend Developer"),
                new UserEntity("Monika", "QA Engineer"),
                new UserEntity("Shalini", "Backend Developer"),
                new UserEntity("Kavya", "Frontend Developer"),
                new UserEntity("Ananya", "Full Stack Developer"),
                new UserEntity("Deepika", "DevOps Engineer"),
                new UserEntity("Nisha", "Backend Developer"),
                new UserEntity("Priyanka", "QA Engineer"),
                new UserEntity("Madhuri", "Frontend Developer"),
                new UserEntity("Sowmya", "Backend Developer"),
                new UserEntity("Aishwarya", "DevOps Engineer"),
                new UserEntity("Chaitra", "Full Stack Developer"),
                new UserEntity("Namrata", "QA Engineer"),
                new UserEntity("Vaishnavi", "Frontend Developer"),
                new UserEntity("Harini", "Backend Developer"),
                new UserEntity("Sanjana", "QA Engineer"),
                new UserEntity("Nikitha", "DevOps Engineer"),
                new UserEntity("Prerana", "Frontend Developer"),
                new UserEntity("Akshata", "Backend Developer"),
                new UserEntity("Tejaswini", "Full Stack Developer"),
                new UserEntity("Ramya", "QA Engineer"),
                new UserEntity("Pavithra", "Frontend Developer"),
                new UserEntity("Sushmita", "Backend Developer"),
                new UserEntity("Amrutha", "DevOps Engineer"),
                new UserEntity("Kruthika", "QA Engineer"),
                new UserEntity("Neetha", "Frontend Developer"),
                new UserEntity("Bhavana", "Backend Developer"),
                new UserEntity("Shilpa", "Full Stack Developer"),
                new UserEntity("Geetha", "QA Engineer"),
                new UserEntity("Usha", "DevOps Engineer"),
                new UserEntity("Rekha", "Frontend Developer"),
                new UserEntity("Jyothi", "Backend Developer"),
                new UserEntity("Sindhu", "Full Stack Developer")
        );
    }
}