spring.application.name=springboot-learning

# =========================
# Local PostgreSQL (Commented)
# =========================
#spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_learning
#spring.datasource.username=postgres
#spring.datasource.password=SR@2timewwechamp
#spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Neon PostgreSQL
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true