spring.application.name=springboot-learning

# =========================
# Local PostgreSQL (Commented)
# =========================
#spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_learning
#spring.datasource.username=postgres
#spring.datasource.password=SR@2timewwechamp
#spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Neon PostgreSQL
# =========================

spring.datasource.url=jdbc:postgresql://ep-morning-haze-aohbzhl8.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gZa9cE6vWOIw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true